1. numpy 설치

    - Python에서 수치 계산을 위한 라이브러리
    - 특징 : 다차원 배열 객체(ndarray)와 다양한 수학 함수를 제공
    - 장점 : 빠르고 효율적인 배열 연산, 많은 과학 및 엔지니어링 애플리케이션에서 활용

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


2. numpy 배열 생성 방법

In [4]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)  # 출력: [1 2 3 4 5]
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
zeros = np.zeros((2, 3))        # 0으로 채워진 2x3 배열
ones = np.ones((2, 3))          # 1로 채워진 2x3 배열
full = np.full((2, 3), 7)       # 7로 채워진 2x3 배열
arange = np.arange(0, 10, 2)    # 0부터 10까지 2 간격으로 배열 생성
linspace = np.linspace(0, 1, 5) # 0부터 1까지 균등 간격으로 5개의 값 생성

print("zeros\n", zeros)
print("ones\n", ones)
print("full\n", full)
print("arange\n", arange)
print("linspace\n", linspace)


zeros
 [[0. 0. 0.]
 [0. 0. 0.]]
ones
 [[1. 1. 1.]
 [1. 1. 1.]]
full
 [[7 7 7]
 [7 7 7]]
arange
 [0 2 4 6 8]
linspace
 [0.   0.25 0.5  0.75 1.  ]


In [5]:
random_array = np.random.rand(3, 3)  # 0과 1 사이의 랜덤 값으로 채워진 3x3 배열
random_int_array = np.random.randint(0, 10, (3, 3))  # 0부터 9 사이의 랜덤 정수로 채워진 3x3 배열

print("random\n", random_array)
print("random_int\n", random_int_array)


random
 [[0.50026895 0.57628871 0.27748006]
 [0.43091519 0.90290906 0.29582819]
 [0.59008521 0.45067202 0.98154955]]
random_int
 [[7 3 8]
 [7 4 8]
 [5 4 9]]


3. numpy 배열 자료형 설정 및 변환

In [19]:
float_array = np.array([1, 2, 3], dtype=float)
print("float\n", float_array)

# 0.x 소수점은 모두 반내림, technic
int_array = float_array.astype(int)
print("int\n", int_array)

float
 [1. 2. 3.]
int
 [1 2 3]


4. numpy 배열의 속성 확인

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)  # 배열의 형태 (2, 3)
print(a.size)   # 배열의 요소 개수 6
print(a.dtype)  # 배열의 자료형 int32
print(a.ndim)   # 배열의 차원 2



(2, 3)
6
int32
2


5. numpy 배열의 요소 접근 및 수정

In [22]:
print("a = \n", a)
print(a[0, 0])  # 첫 번째 행, 첫 번째 열 요소 접근
print(a[1, 2])  # 두 번째 행, 세 번째 열 요소 접근

a[0, 0] = 10    # 첫 번째 행, 첫 번째 열 요소 수정
print("a = \n", a) 


a = 
 [[1 2 3]
 [4 5 6]]
1
6
a = 
 [[10  2  3]
 [ 4  5  6]]


6. numpy 배열 기본 연산

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a + b =", a + b)  # 출력: [5 7 9]
print("a - b =", a - b)  # 출력: [-3 -3 -3]
print("a * b =", a * b)  # 출력: [ 4 10 18]
print("a / b =", a / b)  # 출력: [0.25 0.4  0.5 ]


a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]


7. numpy 배열과 스칼라 값 연산

In [17]:
a = np.array([1, 2, 3])

print(a + 10)  # 출력: [11 12 13]
print(a * 2)   # 출력: [2 4 6]


[11 12 13]
[2 4 6]


8. numpy 기타 함수

In [18]:
a = np.array([1, 2, 3, 4, 5])

print(np.sum(a))   # 배열 요소의 합
print(np.mean(a))  # 배열 요소의 평균
print(np.max(a))   # 배열 요소의 최대값
print(np.min(a))   # 배열 요소의 최소값
print(np.std(a))   # 배열 요소의 표준편차


15
3.0
5
1
1.4142135623730951
