In [37]:
import numpy as np

1. numpy 배열 인덱싱

    - numpy 다차원 배열 인덱싱 예제

In [5]:
np.random.seed(0) # 랜덤 수 고정

arr1 = np.random.randint(10, size=6)
arr2 = np.random.randint(10, size=(2,3))

print("arr1\n", arr1)
print("arr1[0], arr1[-1]\n", arr1[0], arr1[-1])

print("arr2\n", arr2)
print("arr2[0,0], arr2[0,2]\n", arr2[0,0], arr2[0,2])
print("arr2[0,-1], arr2[-1,2]\n", arr2[0,-1], arr2[-1,2])



arr1
 [5 0 3 3 7 9]
arr1[0], arr1[-1]
 5 9
arr2
 [[3 5 2]
 [4 7 6]]
arr2[0,0], arr2[0,2]
 3 2
arr2[0,-1], arr2[-1,2]
 2 6


In [11]:
print("arr2[0,2]\n", arr2[:,1])

arr2[0,2]
 [5 7]


In [20]:
(arr2_int1, arr2_int2) = arr2[:,1]
print(arr2_int1, arr2_int2)

5 7


2. numpy 배열 슬라이싱
    - numpy 배열 슬라이싱 예제

In [22]:
arr1 = np.arange(10)
print("arr1\n", arr1)

print("arr1[0:5:1]\n", arr1[0:5:1])
print("arr1[:5:]\n", arr1[:5:])

print("arr1[5::2]\n", arr1[5::2])
print("arr1[5:-1:2]\n", arr1[5:-1:2])

print("arr1[::-1]\n", arr1[::-1])
print("arr1[-2:-6:-2]\n", arr1[-2:-6:-2])

arr1
 [0 1 2 3 4 5 6 7 8 9]
arr1[0:5:1]
 [0 1 2 3 4]
arr1[:5:]
 [0 1 2 3 4]
arr1[5::2]
 [5 7 9]
arr1[5:-1:2]
 [5 7]
arr1[::-1]
 [9 8 7 6 5 4 3 2 1 0]
arr1[-2:-6:-2]
 [8 6]


In [29]:
print("arr1\n", arr1)
print(arr1[4:7])
print(arr1[-6:-3])

arr1
 [0 1 2 3 4 5 6 7 8 9]
[4 5 6]
[4 5 6]


In [34]:
index_start = int(len(arr1)/3)

print(arr1[index_start:index_start*-1])

[3 4 5 6]


In [39]:
arr2 = np.arange(12)
print("arr2\n", arr2.shape)

reshaped_arr2 = arr2.reshape(4,3)
print("reshaped_arr2\n", reshaped_arr2.shape)

reshaped_arr2_ver2 = arr2.reshape(-1,3)
print("reshaped_arr2_ver2\n", reshaped_arr2_ver2.shape)

reshaped_arr2_ver3 = arr2.reshape(3,-1)
print("reshaped_arr2_ver3\n", reshaped_arr2_ver3.shape)

print("reshaped_arr2_ver2\n", reshaped_arr2_ver2)
print("reshaped_arr2_ver2[:2,:2]\n", reshaped_arr2_ver2[:2,:2])
print("reshaped_arr2_ver2[1:3,:2]\n", reshaped_arr2_ver2[1:3,:2])
print("reshaped_arr2_ver2[1:-1,1:-1]\n", reshaped_arr2_ver2[1:-1,1:-1])
print("reshaped_arr2_ver2[-1:,:]\n", reshaped_arr2_ver2[-1:,:]) # 슬라이싱은 [[]]
print("reshaped_arr2_ver2[-1]\n", reshaped_arr2_ver2[-1]) # 인덱싱은 []

arr2
 (12,)
reshaped_arr2
 (4, 3)
reshaped_arr2_ver2
 (4, 3)
reshaped_arr2_ver3
 (3, 4)
reshaped_arr2_ver2
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
reshaped_arr2_ver2[:2,:2]
 [[0 1]
 [3 4]]
reshaped_arr2_ver2[1:3,:2]
 [[3 4]
 [6 7]]
reshaped_arr2_ver2[1:-1,1:-1]
 [[4]
 [7]]
reshaped_arr2_ver2[-1:,:]
 [[ 9 10 11]]
reshaped_arr2_ver2[-1]
 [ 9 10 11]


In [45]:
arr2_try = np.arange(12)
arr2_try_reshape_1 = arr2_try.reshape(2,6)
arr2_try_reshape_2 = arr2_try.reshape(-1,6)
arr2_try_reshape_3 = arr2_try.reshape(2,-1)
print("arr2_try_reshape_1:\n", arr2_try_reshape_1)
print("arr2_try_reshape_2:\n", arr2_try_reshape_2)
print("arr2_try_reshape_3:\n", arr2_try_reshape_3)

arr2_try_reshape_1:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr2_try_reshape_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
arr2_try_reshape_3:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


3. numpy 배열 팬시 인덱싱

In [59]:
arr_1 = np.arange(12).reshape((3,4))
print("arr_1\n",arr_1)

row = np.arange(3)
col = np.arange(1, 4)

print("row\n", row)
print("col\n", col)

print("arr_1[row]\n", arr_1[row])
print("arr_1[:,col]\n", arr_1[:,col])
print("arr_1[row,col]\n", arr_1[row,col]) # 행렬 계산

print("row.reshape(-1,1)\n", row.reshape(-1,1))
print("arr_1[row.reshape(-1,1),col]\n", arr_1[row.reshape(-1,1),col])

arr_1
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
row
 [0 1 2]
col
 [1 2 3]
arr_1[row]
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
arr_1[:,col]
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
arr_1[row,col]
 [ 1  6 11]
row.reshape(-1,1)
 [[0]
 [1]
 [2]]
arr_1[row.reshape(-1,1),col]
 [[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [61]:
# 어레인지 16, 4,4
array_try = np.arange(16).reshape(4,-1)
print(array_try)


row = np.arange(1,3)
col = np.arange(1,3)
print(row.reshape(-1,1))
print(col.reshape(-1,1))

print("array_try[row,col]\n", array_try[row.reshape(-1,1),col])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[1]
 [2]]
[[1]
 [2]]
array_try[row,col]
 [[ 5  6]
 [ 9 10]]


4. numpy 배열의 복합 인덱싱

In [62]:
arr_1 = np.zeros(12).reshape((3,4))
print("arr_1\n", arr_1)

arr_1[0,1] = 1
print("arr_1\n", arr_1)

arr_1[1,[1,3]] = 2
print("arr_1\n", arr_1)

arr_1[[0,2],[2,3]] = 3
print("arr_1\n", arr_1)

arr_1 = np.zeros(12).reshape((3,4))
print("arr_1\n", arr_1)

arr_1[1:-1,[2,3]] = 3
print("arr_1\n", arr_1)

arr_1[[0,2],1:3] = 4
print("arr_1\n", arr_1)


arr_1
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arr_1
 [[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arr_1
 [[0. 1. 0. 0.]
 [0. 2. 0. 2.]
 [0. 0. 0. 0.]]
arr_1
 [[0. 1. 3. 0.]
 [0. 2. 0. 2.]
 [0. 0. 0. 3.]]
arr_1
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
arr_1
 [[0. 0. 0. 0.]
 [0. 0. 3. 3.]
 [0. 0. 0. 0.]]
arr_1
 [[0. 4. 4. 0.]
 [0. 0. 3. 3.]
 [0. 4. 4. 0.]]
