In [1]:
import numpy as np

1. numpy 배열 bool 마스킹

In [4]:
np.random.seed(0) # 랜덤 수 고정

arr1 = np.random.randint(1, 10, size=(3,4))

print("arr1\n", arr1)

print("arr1>4\n", (arr1 > 4))
print("arr1<7\n", (arr1 < 7))
print("arr1>4 & arr1<7\n", (arr1 > 4) & (arr1 < 7))

print("sum arr1>4 & arr1<7\n", np.sum((arr1 > 4) & (arr1 < 7)))
print("sum(axis=0) arr1>4 & arr1<7\n", np.sum((arr1 > 4) & (arr1 < 7), axis=0)) # 세로로, row 방향
print("sum(axis=1) arr1>4 & arr1<7\n", np.sum((arr1 > 4) & (arr1 < 7), axis=1)) # 가로로, col 방향

print("arr1[(arr1 > 4) & (arr1 < 7)]\n", arr1[(arr1 > 4) & (arr1 < 7)])
print(type(arr1[(arr1 > 4) & (arr1 < 7)]))
print("sum arr1>4 | arr1<7\n", np.sum((arr1 > 4) | (arr1 < 7)))


arr1
 [[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]
arr1>4
 [[ True False False False]
 [ True False  True False]
 [ True  True  True  True]]
arr1<7
 [[ True  True  True  True]
 [False  True  True  True]
 [ True False False False]]
arr1>4 & arr1<7
 [[ True False False False]
 [False False  True False]
 [ True False False False]]
sum arr1>4 & arr1<7
 3
sum(axis=0) arr1>4 & arr1<7
 [2 0 1 0]
sum(axis=1) arr1>4 & arr1<7
 [1 1 1]
arr1[(arr1 > 4) & (arr1 < 7)]
 [6 6 5]
<class 'numpy.ndarray'>
sum arr1>4 | arr1<7
 12


2. numpy 배열 where
    - numpy 배열 where 예제

In [29]:
np.random.seed(0) # 랜덤 수 고정

arr1 = np.random.randint(1, 10, size=(3,4))

print("arr1\n", arr1)

print("arr1>4\n", np.where(arr1 > 4))
print("arr1[arr1>4]\n", arr1[np.where(arr1 > 4)])
print("np.where(arr1>4, np.max(arr1), arr1)\n", np.where(arr1 > 4, np.max(arr1), arr1))
print("arr1<7\n", np.where(arr1 < 7))
print("arr1[arr1<7]\n", arr1[np.where(arr1 < 7)])
print("np.where(arr1<7, np.min(arr1), arr1)\n", np.where(arr1 < 7, np.min(arr1), arr1))

arr1
 [[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]
arr1>4
 (array([0, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 0, 2, 0, 1, 2, 3], dtype=int64))
arr1[arr1>4]
 [6 8 6 5 8 7 9]
np.where(arr1>4, np.max(arr1), arr1)
 [[9 1 4 4]
 [9 4 9 3]
 [9 9 9 9]]
arr1<7
 (array([0, 0, 0, 0, 1, 1, 1, 2], dtype=int64), array([0, 1, 2, 3, 1, 2, 3, 0], dtype=int64))
arr1[arr1<7]
 [6 1 4 4 4 6 3 5]
np.where(arr1<7, np.min(arr1), arr1)
 [[1 1 1 1]
 [8 1 1 1]
 [1 8 7 9]]


3. numpy 배열 where 복수 조건

In [34]:
np.random.seed(0) # 랜덤 수 고정

arr1 = np.random.randint(1, 10, size=(3,4))

print("arr1\n", arr1)

print("arr1>4\n", np.where(arr1 > 4))
print("arr1<7\n", np.where(arr1 < 7))
print("arr1>4 & arr1<7\n", np.where((arr1 > 4) & (arr1 < 7)))
print("np.where((arr1>4) & (arr1<7), 0, arr1)\n", np.where((arr1 > 4) & (arr1 < 7), 0, arr1))
print("np.where((arr1>4) | (arr1<7), 0, arr1)\n", np.where((arr1 > 4) | (arr1 < 7), 0, arr1))
print("np.where((arr1<4) | (arr1>7), 0, arr1)\n", np.where((arr1 < 4) | (arr1 > 7), 0, arr1))

arr1
 [[6 1 4 4]
 [8 4 6 3]
 [5 8 7 9]]
arr1>4
 (array([0, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 0, 2, 0, 1, 2, 3], dtype=int64))
arr1<7
 (array([0, 0, 0, 0, 1, 1, 1, 2], dtype=int64), array([0, 1, 2, 3, 1, 2, 3, 0], dtype=int64))
arr1>4 & arr1<7
 (array([0, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))
np.where((arr1>4) & (arr1<7), 0, arr1)
 [[0 1 4 4]
 [8 4 0 3]
 [0 8 7 9]]
np.where((arr1>4) | (arr1<7), 0, arr1)
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
np.where((arr1<4) | (arr1>7), 0, arr1)
 [[6 0 4 4]
 [0 4 6 0]
 [5 0 7 0]]


4. numpy 배열 where 심화

In [6]:
arr1 = np.arange(1,10)
print("arr1\n", arr1)

reshaped_arr1 = arr1.reshape(-1,3)
print("reshaped_arr1\n", reshaped_arr1)

print("np.where((np.sum(reshaped_arr1, axis=0) > 15).reshape(3,-1), reshaped_arr1, 0)\n", np.where((np.sum(reshaped_arr1, axis=0) > 15).reshape(3,-1), reshaped_arr1, 0))
print("np.where((np.sum(reshaped_arr1, axis=1) > 10).reshape(3,-1), reshaped_arr1, 0)\n", np.where((np.sum(reshaped_arr1, axis=1) > 10).reshape(3,-1), reshaped_arr1, 0))
odd_arr = np.where(reshaped_arr1 % 2 == 1, reshaped_arr1, 0)
print("odd_arr\n", odd_arr)
print("np.where((np.sum(reshaped_arr1, axis=1) > 10).reshape(3,-1), np.where( reshaped_arr1 % 2 == 1, reshaped_arr1, 0), 0)\n", np.where((np.sum(reshaped_arr1, axis=1) > 10).reshape(3,-1), odd_arr, 0))

arr1
 [1 2 3 4 5 6 7 8 9]
reshaped_arr1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
np.where((np.sum(reshaped_arr1, axis=0) > 15).reshape(3,-1), reshaped_arr1, 0)
 [[0 0 0]
 [0 0 0]
 [7 8 9]]
np.where((np.sum(reshaped_arr1, axis=1) > 10).reshape(3,-1), reshaped_arr1, 0)
 [[0 0 0]
 [4 5 6]
 [7 8 9]]
odd_arr
 [[1 0 3]
 [0 5 0]
 [7 0 9]]
np.where((np.sum(reshaped_arr1, axis=1) > 10).reshape(3,-1), np.where( reshaped_arr1 % 2 == 1, reshaped_arr1, 0), 0)
 [[0 0 0]
 [0 5 0]
 [7 0 9]]
